### PR TITLE
Modify namespace and class file names to suite the PSR-4 autoloading …

### PR DESCRIPTION
**Pull request by remluben**
…(case sensitive) as defined in composer.json as well as files matching the cases sensitiv class names.

This pull request refers to the original issue opened at https://github.com/AJRepo/PHPlot/issues/9 

What I did and why I did it: I made fixes to the namespace and class file names, which should be case sensitive when sticking to the PSR-4 autoloading with composer. 

I tried to change all occurences of the old namespace written as `PHPlot\PHPlot` instead of `Phplot\Phplot` (as defined in composer.json)

Please let me know if this is a possible solution for you to make the package more conform and also solve the original issues as described in https://github.com/AJRepo/PHPlot/issues/9 

I am looking forward to your reply,

kind regards
Benjamin

### CODE REVIEW

**Comment by AJRepo** [comment]
Thanks! Getting some feedback on this from some other users.

**Comment by remluben** [comment]
Hey, I just wanted to ask about the current state. Did you get in touch with other developers so far? Can I help you with anything so we can continue with this pull request?

I am looking forward to your reply.

Keep on the good work.

Kind regards,
Benjamin.

**Comment by AJRepo** [comment]
Hi - when you talk to N developers apparently you get 2N suggestions. One was yours, One was changing the name of the file, one was changing the composer file, and a few as variations of those.  One said he's submit a PR as a comparison, but hasn't yet. So I wrote a program to test all of those PHPlot/Phplot/phplot suggested permutations of file/composer/path  suggestions ...  (3^2)(3^3) = 243 permutations. 

Some of the suggestions didn't agree with the tests, and your suggestion is one that means existing installs don't have a file case change, so I'm 99% sure I'm going to merge your PR. Just waiting to hear back from one developer to make sure I'm not missing something. 

Thanks!

**Comment by remluben** [comment]
Hey, 

thank you for your feedback and for putting so much effort into it. I am glad to hear my PR seems to be a suitable solution.

I am looking forward to the solution.

Thanks!

**Comment by cth18012017** [comment]
Hello, in our big project we use this  composer configuration:

"require" : {
"phplot/phplot" : "^8.0"
}

**Comment by remluben** [comment]
> Hello, in our big project we use this composer configuration:
> 
> "require" : { "phplot/phplot" : "^8.0" }

Hello and thanks for your feedback @cth18012017 

* Did you run into any issues?
* What version of PHP + Composer are you using?
* What OS are you on?

**Comment by AJRepo** [comment]
Hello @cth18012017 : Do you use 

`require 'vendor/autoload.php';` or  `require 'src/phplot.php';` 

 Thank you both for your help. 

I've been testing out how this change impacts existing installations.  

The two ways people are implementing this  class (that I know of) are: 

* `composer require  phplot/phplot` and  (`require 'vendor/autoload.php';`) 
* `require 'src/phplot.php';` 

Calling as `require 'src/phplot.php';` has no impact to case sensitivity in calling the vendorname\namespace\class

Calling using composer autoload with PSR-4 does have  a case sensitivity issue and it's affected by the case of the actual file. 

There are 712 permutations of  filename_case, Composer.json_case, vendor\namespace\class case

For PSR-4 implementation of: 
  filename=[Pp][Hh][Pp]lot.php 
  src composer.json PSR-4 call of  [Pp][Hh][Pp]lot\\[Pp][Hh][Pp]lot\\
  calling `$plot = new \[Pp][Hh][Pp]lot\[Pp][Hh][Pp]lot\[Pp][Hh][Pp]lot(80,60);`

we get, for using autoload: 

```
Filename=phplot.php: Composer.json=phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\Phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\Phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new phplot\Phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new phplot\PHPlot\phplot(80, 60)
Filename=Phplot.php: Composer.json=phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new phplot\PHPlot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new phplot\PHPlot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=Phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=Phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=Phplot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=Phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\Phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=Phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\Phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=Phplot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\Phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=Phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\PHPlot\phplot(80, 60)
Filename=Phplot.php: Composer.json=Phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\PHPlot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=Phplot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new Phplot\PHPlot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=PHPlot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=PHPlot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=PHPlot\\phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=PHPlot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\Phplot\phplot(80, 60)
Filename=Phplot.php: Composer.json=PHPlot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\Phplot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=PHPlot\\Phplot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\Phplot\PHPlot(80, 60)
Filename=phplot.php: Composer.json=PHPlot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\PHPlot\phplot(80, 60)
Filename=Phplot.php: Composer.json=PHPlot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\PHPlot\Phplot(80, 60)
Filename=PHPlot.php: Composer.json=PHPlot\\PHPlot\\ AUTOLOAD_SUCCESS= $plot=new PHPlot\PHPlot\PHPlot(80, 60)
```

All of the above is without changing any code in the file phplot.php.

Some feedback I've gotten is that changing the case of the file phplot.php would be disruptive for those who use git clone and `require 'src/phplot.php';` 

So keeping the filename as phplot.php might be important at this junction to have minimal forward changes. 

If staying with PSR-4 and keeping the filename as phplot.php (lowercase) that leaves a few options like: 

1) Leave composer as is -> 
          Change existing code and specify in docs that calls should be  `$plot=new Phplot\Phplot\phplot($x,$y)` 

2) Change composer to PHPlot\\PHPlot\\ -> 
         Change existing code and specify in docs that calls should be  `$plot=new PHPlot\PHPlot\phplot($x,$y)` 

3) Change composer to phplot\\phplot\\ -> 
         Change existing code and specify in docs that calls should be  `$plot=new phplot\phplot\phplot($x,$y)` 

Thoughts?

**Comment by remluben** [comment]
Hello. 

Thanks for pointing out that there is no issue if using `include` or `require` vs. problems using composer. Probably that's also why many developers do not run into issues.

For your suggestions. I like every single suggestion of them 👍 

I think my personal preference would be 1. `Phplot\Phplot\phplot()`

Kind regards,
Benjamin.

**Comment by AJRepo** [comment]
Let's go with (1). If you want to re-submit with those changes I'll work on a CI that tests it. Thanks!

**Comment by remluben** [comment]
Hello @AJRepo,

I made the changes now. The new fully qualified class names are 

* `Phplot\Phplot\phplot` and
* `Phplot\Phplot\phplot_truecolor`

now. I am looking forward to the new version of the library so I can use it via composer correctly. 👍 

Kind regards.

**Comment by AJRepo** [comment]
Looks pretty good. I thought I could pull this into development to merge it with the CI tests I've written, but not so easily unless you point the merge toward the development branch. Can you change the PR toward development instead of master?

**Comment by remluben** [comment]
> Looks pretty good. I thought I could pull this into development to merge it with the CI tests I've written, but not so easily unless you point the merge toward the development branch. Can you change the PR toward development instead of master?

Done. Sorry for opening the PR for master in my first try.

**Comment by AJRepo** [comment]
Rebase and merge into branch develop.

**Comment by remluben** [comment]
Thanks for merging and your support. I will use the develop and switch to your next release version as soon as available. I am looking forward to it. 🥇

**Comment by AJRepo** [comment]
Thanks for your help! Released to packagist/composer also.

**Pull request merged**
